File "./theories/FSets/FSetPositive.v", line 319, characters 9-25:
Warning:
Tactician found a bug in it's tactical decomposition. Please report.
intros s x y ->
intros s;
 (intros x;
   (intros y;
     (intros _tmp_tactician0; (intropattern subst -> _tmp_tactician0; idtac))))

Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
File "./theories/Reals/RiemannInt.v", line 742, characters 2-159:
Warning: Tactician's tactical decomposition crashed. Please report.
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
Traceback (most recent call last):
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/bin/g2t-server", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server')())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/loader/predict_server.py", line 706, in main
    predict = Predict(Path(args.model).expanduser().absolute())
  File "/tmp/tactician.tmp.c0elVt/target-source/venv/lib/python3.9/site-packages/graph2tac/tfgnn/predict.py", line 155, in __init__
    with graph_constants_filepath.open('r') as yml_file:
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/dccstor/mathzero/benchmark2/venv/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-graph2tac/config/graph_constants.yaml'
File "./theories/Reals/Rdefinitions.v", line 165, characters 2-9:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/NArith/Ndec.v", line 225, characters 2-9:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/FSets/FSetProperties.v", line 68, characters 9-17:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/setoid_ring/InitialRing.v", line 178, characters 2-15:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/ZArith/Znumtheory.v", line 54, characters 7-28:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/FSets/FMapFacts.v", line 289, characters 0-6:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/FSets/FSetPositive.v", line 841, characters 9-22:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/ZArith/Zpower.v", line 172, characters 3-49:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/NArith/Ndigits.v", line 116, characters 1-25:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/RIneq.v", line 205, characters 7-48:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Ranalysis4.v", line 300, characters 2-8:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/ZArith/Znat.v", line 570, characters 1-11:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/ZArith/auxiliary.v", line 74, characters 1-16:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/FSets/FSetCompat.v", line 333, characters 9-54:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/MSets/MSetFacts.v", line 39, characters 7-33:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Numbers/Cyclic/Int63/Int63.v", line 833, characters 1-68:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/QArith/QArith_base.v", line 626, characters 1-12:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Numbers/DecimalPos.v", line 227, characters 1-108:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/ZArith/Zdiv.v", line 596, characters 2-47:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/RList.v", line 413, characters 2-21:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/ConstructiveRealsMorphisms.v", line 402, characters 2-14:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/RiemannInt_SF.v", line 1470, characters 2-262:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Rtrigo1.v", line 134, characters 2-79:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Rbasic_fun.v", line 472, characters 2-143:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Numbers/Cyclic/ZModulo/ZModulo.v", line 73, characters 2-61:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Rseries.v", line 105, characters 4-28:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/micromega/OrderedRing.v", line 347, characters 0-11:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/micromega/ZMicromega.v", line 51, characters 2-17:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/FSets/FSetEqProperties.v", line 315, characters 0-14:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/MSets/MSetProperties.v", line 82, characters 9-17:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/MSets/MSetAVL.v", line 657, characters 1-215:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/RiemannInt.v", line 1495, characters 2-379:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/setoid_ring/Field_theory.v", line 1039, characters 1-10:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/ConstructiveCauchyReals.v", line 1218, characters 2-22:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/MSets/MSetPositive.v", line 487, characters 4-14:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/nsatz/Nsatz.v", line 482, characters 0-12:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/setoid_ring/Ring_polynom.v", line 1436, characters 2-40:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/FSets/FMapAVL.v", line 1364, characters 1-38:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/micromega/EnvRing.v", line 1082, characters 3-10:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/MSets/MSetRBT.v", line 1523, characters 1-18:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

Abnormal exit code for coqc: 129
 Invocation:
(cd /tmp/tactician.tmp.c0elVt/opam-root/bench/.opam-switch/build/coq-tactician-stdlib.8.11.dev && bwrap --dev-bind / / --bind /tmp/tactician.tmp.c0elVt/opam-root/bench/.opam-switch/build/coq-tactician-stdlib.8.11.dev/theories/FSets/FSetCompat.vo.bench /tmp/tactician.tmp.c0elVt/opam-root/bench/.opam-switch/build/coq-tactician-stdlib.8.11.dev/theories/FSets/FSetCompat.vo /tmp/tactician.tmp.c0elVt/opam-root/bench/bin/coqc -q -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/coq/user-contrib/Tactician -R /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/coq/user-contrib/Tactician Tactician -rifrom Tactician Ltac1.Record -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/stdlib-shims -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/ocamlgraph -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/ocaml -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/lwt -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/ocplib-endian -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/ocplib-endian/bigstring -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/lwt/unix -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/astring -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/res -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/result -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/stdint -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/capnp -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/asetmap -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/fmt -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/logs -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/capnp-rpc -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/bigstringaf -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/angstrom -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/stringext -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/uri -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/capnp-rpc-lwt -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/base64 -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/cstruct -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/eqaf -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/eqaf/bigstring -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/eqaf/cstruct -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/mirage-crypto -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/mirage-crypto-rng -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/mirage-flow -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/re -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/prometheus -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/ptime -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/mirage-clock -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/sexplib0 -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/zarith -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/mirage-crypto-pk -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/mirage-kv -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/base/caml -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/parsexp -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/sexplib -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/cstruct-sexp -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/domain-name -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/hkdf -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/macaddr -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/ipaddr -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/ppx_sexp_conv/runtime-lib -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/ipaddr-sexp -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/mirage-crypto-ec -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/asn1-combinators -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/gmap -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/pbkdf -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/x509 -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/tls -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/tls-mirage -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/capnp-rpc-net -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/cmdliner -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/cstruct-lwt -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/extunix -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/duration -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/mirage-crypto-rng/unix -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/mtime -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/mtime/clock/os -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/mirage-crypto-rng/lwt -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/capnp-rpc-unix -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/base/base_internalhash_types -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/base/shadow_stdlib -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/base -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/stdio -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/capnp/unix -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/logs -l NNLearner -l Graph2TacConfig.v -l /tmp/tactician.tmp.c0elVt/opam-root/bench/share/coq-tactician/plugins/zzz-benchmark/Injections.v -q -coqlib . -I /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/coq/user-contrib/Tactician -R /tmp/tactician.tmp.c0elVt/opam-root/bench/lib/coq/user-contrib/Tactician Tactician -rifrom Tactician Ltac1.Record theories/FSets/FSetCompat.v -l /tmp/tactician.tmp.c0elVt/BenchParams.v)