2023-01-11 15:28:54.610722: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-11 15:28:54.653109: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-11 15:28:54.981908: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-11 15:28:55.856414: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-01-11 15:28:55.856522: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-01-11 15:28:55.856534: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-11 15:28:55.857719: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-01-11 15:28:55.857810: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-01-11 15:28:55.857821: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-11 15:28:55.971371: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-11 15:28:56.243021: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-01-11 15:28:56.243119: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-01-11 15:28:56.243130: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-11 15:28:57.392104: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-01-11 15:28:57.392216: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-01-11 15:28:57.392228: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/tactician_final/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/tactician_final/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 47, in <module>
    graph_api_capnp = capnp.load(graph_api_filename)
  File "capnp/lib/capnp.pyx", line 4365, in capnp.lib.capnp.load
  File "capnp/lib/capnp.pyx", line 3561, in capnp.lib.capnp.SchemaParser.load
OSError: File not found: /raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/clib/graph_api_v14.capnp
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/tactician_final/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/tactician_final/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 47, in <module>
    graph_api_capnp = capnp.load(graph_api_filename)
  File "capnp/lib/capnp.pyx", line 4365, in capnp.lib.capnp.load
  File "capnp/lib/capnp.pyx", line 3561, in capnp.lib.capnp.SchemaParser.load
OSError: File not found: /raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/clib/graph_api_v14.capnp
Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/tactician_final/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/tactician_final/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 47, in <module>
    graph_api_capnp = capnp.load(graph_api_filename)
  File "capnp/lib/capnp.pyx", line 4365, in capnp.lib.capnp.load
  File "capnp/lib/capnp.pyx", line 3561, in capnp.lib.capnp.SchemaParser.load
OSError: File not found: /raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/clib/graph_api_v14.capnp
File "./theories/Reals/Ranalysis1.v", line 917, characters 2-51:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Reals/Ranalysis4.v", line 369, characters 2-44:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.ECONNRESET, "read", "")."
Please report at http://coq.inria.fr/bugs/.

Traceback (most recent call last):
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/bin/g2t-server-text", line 33, in <module>
    sys.exit(load_entry_point('graph2tac==0.1.0', 'console_scripts', 'g2t-server-text')())
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/bin/g2t-server-text", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/piepejel/anaconda3/envs/tactician_final/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/piepejel/anaconda3/envs/tactician_final/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/lib/python3.10/site-packages/graph2tac/transformer/pserver.py", line 47, in <module>
    graph_api_capnp = capnp.load(graph_api_filename)
  File "capnp/lib/capnp.pyx", line 4365, in capnp.lib.capnp.load
  File "capnp/lib/capnp.pyx", line 3561, in capnp.lib.capnp.SchemaParser.load
OSError: File not found: /raid/scratch/piepejel/projects/coq-benchmarks/target-source/venv/lib/python3.10/site-packages/graph2tac/loader/clib/graph_api_v14.capnp
File "./theories/Reals/Rgeom.v", line 192, characters 2-71:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

File "./plugins/micromega/RMicromega.v", line 398, characters 2-9:
Error:
Anomaly "Uncaught exception Unix.Unix_error(Unix.EPIPE, "single_write", "")."
Please report at http://coq.inria.fr/bugs/.

