  Running command git clone --filter=blob:none --quiet https://github.com/IBM/graph2tac.git /tmp/pip-req-build-r12_j8mt
  Running command git rev-parse -q --verify 'sha^16ef6b8c72d9a027c3fd025f230a6fd2313b20eb'
  Running command git fetch -q https://github.com/IBM/graph2tac.git 16ef6b8c72d9a027c3fd025f230a6fd2313b20eb
  Running command git checkout -q 16ef6b8c72d9a027c3fd025f230a6fd2313b20eb
  Running command git clone --filter=blob:none --quiet 'https://****@github.com/coq-tactician/coq-tactician-reinforce' /tmp/pip-install-a3fst42k/pytact_9528f60ed1ed48c78a37dcd190bab5ff
  Running command git submodule update --init --recursive -q

[notice] A new release of pip available: 22.2.1 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
[ERROR] Failed to get extra source "model.tar.gz" of coq-graph2tac.~dev: Bad checksum

#=== ERROR while fetching sources for coq-graph2tac.~dev ======================#
OpamSolution.Fetch_fail("http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-01-08_E_tfgnn_v13-shared_stdlib_recompute-emb_no-def-name_epoch68.b99a366f16bf061518fc692f09dc7b10.tar.gz (Bad checksum, expected md5=e8bf2600b8010b6a42d9f3ed399d7c6d)")
